name: Create/Upload HF Space
on:
  push:
  workflow_dispatch:

jobs:
  create-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface-hub

      - name: Run space creation & upload script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: ${{ secrets.HF_USER }}
        run: |
          python create_space_and_upload.py
